name: Deploy Workflow

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Compute variables
        id: set-vars
        env: 
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "DEBUG: ENV_VARS=$ENV_VARS"
          ENV_FLAGS=$(echo "$ENV_VARS" | tr ' ' '\n' | awk '{print "-e " $1}' | paste -sd ' ' -)
          REF="${{ github.ref }}"
          TAG_NAME="${REF##*/}"
          REPO_NAME="${{ github.event.repository.name }}"
          CONTAINER_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${CONTAINER_NAME}:${TAG_NAME}"

          echo "DEBUG: ENV_FLAGS=$ENV_FLAGS"
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "container-name=${CONTAINER_NAME}" >> $GITHUB_ENV
          echo "env-flags=${ENV_FLAGS}" >> $GITHUB_ENV

      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}" .
          docker push "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Pulling image"
            docker pull "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

            echo "Checking if container ${{ env.container-name }} exists..."
            if [ "$(docker ps -aq -f name=^${{ env.container-name }}$)" ]; then
              echo "Stopping and removing existing container..."
              docker stop "${{ env.container-name }}"
              docker rm "${{ env.container-name }}"
            else
              echo "No existing container found."
            fi

            echo "Running new container..."
            docker run -d \
              --restart unless-stopped \
              -p "${{ secrets.EXPOSED_PORT }}:${{ secrets.INTERNAL_PORT }}" \
              --name "${{ env.container-name }}" \
              ${{ env.env-flags }} \
              "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

            echo "Deployment complete."
