name: Deploy Workflow

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Compute variables
        id: set-vars
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          # Print ENV_VARS for debugging
          echo "DEBUG: ENV_VARS=$ENV_VARS"

          # Prepare build-args string by extracting all NEXT_PUBLIC_* variables from ENV_VARS
          BUILD_ARGS=""
          for VAR in $(echo "$ENV_VARS" | tr ' ' '\n'); do
            if [[ "$VAR" =~ ^NEXT_PUBLIC_ ]]; then
              BUILD_ARGS="$BUILD_ARGS --build-arg $VAR"
            fi
          done

          # Prepare runtime flags for docker run (all env vars passed as -e), excluding NEXT_PUBLIC_* variables
          ENV_FLAGS=""
          for VAR in $(echo "$ENV_VARS" | tr ' ' '\n'); do
            if [[ ! "$VAR" =~ ^NEXT_PUBLIC_ ]]; then
              ENV_FLAGS="$ENV_FLAGS -e $VAR"
            fi
          done

          # Debugging output to verify extracted arguments
          echo "DEBUG: BUILD_ARGS=$BUILD_ARGS"
          echo "DEBUG: ENV_FLAGS=$ENV_FLAGS"

          # Prepare other environment variables and container name
          REF="${{ github.ref }}"
          TAG_NAME="${REF##*/}"
          REPO_NAME="${{ github.event.repository.name }}"
          CONTAINER_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${CONTAINER_NAME}:${TAG_NAME}"

          echo "DEBUG: IMAGE_NAME=$IMAGE_NAME"
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "container-name=${CONTAINER_NAME}" >> $GITHUB_ENV
          echo "build-args=${BUILD_ARGS}" >> $GITHUB_ENV
          echo "env-flags=${ENV_FLAGS}" >> $GITHUB_ENV

      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Build Docker image and dynamically inject all NEXT_PUBLIC_* variables as build arguments
          docker build ${{ env.build-args }} -t "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}" .
          docker push "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Pulling image"
            docker pull "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

            echo "Checking if container ${{ env.container-name }} exists..."
            if [ "$(docker ps -aq -f name=^${{ env.container-name }}$)" ]; then
              echo "Stopping and removing existing container..."
              docker stop "${{ env.container-name }}"
              docker rm "${{ env.container-name }}"
            else
              echo "No existing container found."
            fi

            echo "Running new container..."
            docker run -d \
              --restart unless-stopped \
              -p "${{ secrets.EXPOSED_PORT }}:${{ secrets.INTERNAL_PORT }}" \
              --name "${{ env.container-name }}" \
              ${{ env.env-flags }} \
              "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

            echo "Deployment complete."

