name: Deploy Workflow

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Prepare variables and build args
        id: prep
        run: |
          set -euo pipefail

          BUILD_ARGS=""
          ENV_FILE=""

          for VAR in $(env); do 
            if [[ "$VAR" =~ ^ARG_ ]]; then 
              NAME=${VAR#ARG_}
              BUILD_ARGS="$BUILD_ARGS --build-arg ${NAME}=${!VAR}"
            fi

            if [[ "$VAR" =~ ^ENV_ ]]; then 
              NAME=${VAR#ENV_}
              ENV_FILE="$ENV_FILE${NAME}=${!VAR}\n" 
            fi
          done

          REF="${{ github.ref }}"
          TAG_NAME="${REF##*/}"
          REPO_NAME="${{ github.event.repository.name }}"
          CONTAINER_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${CONTAINER_NAME}:${TAG_NAME}"
          RELEASE_DIR="${{ secrets.BASE_DEPLOY_PATH }}${CONTAINER_NAME}/${TAG_NAME}"

          ENV_FILE="${ENV_FILE}IMAGE_TAG=${TAG_NAME}\n"

          echo -e "$ENV_FILE" > .env.gen

          echo "image-name=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "container-name=${CONTAINER_NAME}" >> $GITHUB_ENV
          echo "build-args=${BUILD_ARGS}" >> $GITHUB_ENV
          echo "release-dir=${RELEASE_DIR}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          set -euo pipefail
          docker build -f Dockerfile.prod ${{ env.build-args }} -t "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}" .
          docker push "${{ secrets.DOCKER_REPO }}/${{ env.image-name }}"

      - name: Upload docker-compose file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: |
            ./docker-compose.prod.yml
            ./env.gen
          target: "${{ env.release-dir }}"
          strip_components: 0
          pre-script: |
            mkdir -p "${{ env.release-dir }}"

      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail

            cd "${{ env.release-dir }}"

            mv .env.gen .env 
            mv docker-compose.prod.yml docker-compose.yml 
            chmod 600 .env 
            chmod 644 docker-compose.yml

            docker compose up -d --pull always --remove-orphans

            echo "Deployment complete."
